// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hetgzarwcyyawyrylnjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldGd6YXJ3Y3l5YXd5cnlsbmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDAzOTMsImV4cCI6MjA2OTIxNjM5M30.9KfSAGSiixH4gq5LCWaYTFmDFQM8OHtUQ91PtavLKCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});